services:
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  account:
    build:
      context: ./account
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - MQ_HOSTNAME=rabbitmq
      - CUSTOMER_API=http://localhost:8082
      - MERCHANT_API=http://localhost:8086
      - MANAGER_API=http://localhost:8087

  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    environment:
      - MQ_HOSTNAME=rabbitmq
      - MERCHANT_API=http://localhost:8086
      - MANAGER_API=http://localhost:8087

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - MQ_HOSTNAME=rabbitmq
      - CUSTOMER_API=http://localhost:8082
      - MERCHANT_API=http://localhost:8086
      - MANAGER_API=http://localhost:8087

  token:
    build:
      context: ./token
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - MQ_HOSTNAME=rabbitmq
      - CUSTOMER_API=http://localhost:8082
      - MERCHANT_API=http://localhost:8086
      - MANAGER_API=http://localhost:8087

  reporting:
    build:
      context: ./reporting
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - MQ_HOSTNAME=rabbitmq
      - CUSTOMER_API=http://localhost:8082
      - MERCHANT_API=http://localhost:8086
      - MANAGER_API=http://localhost:8087

  merchant:
    build:
      context: ./merchant
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - rabbitmq
    environment:
      - MQ_HOSTNAME=rabbitmq
      - CUSTOMER_API=http://localhost:8082
      - MANAGER_API=http://localhost:8087

  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    depends_on:
      - rabbitmq
    environment:
      - MQ_HOSTNAME=rabbitmq
      - CUSTOMER_API=http://localhost:8082
      - MERCHANT_API=http://localhost:8086

