services:
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  account:
    build:
      context: ./account
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - rabbitmq
  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - rabbitmq
  token:
    build:
      context: ./token
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    depends_on:
      - rabbitmq
