POST http://localhost:8080/accounts
Content-Type: application/json
Accept: application/json

{
  "id": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  },
  "name": "John Doe",
  "cpr": "123456-7890",
  "bankAccountNo": {
    "bankAccountNo": "test"
  }
}